FROM node:24-alpine AS build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.29-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/sleep-edfx-web/browser /usr/share/nginx/html
EXPOSE 4200

USER nginx
CMD ["nginx", "-g", "daemon off;"]
